name: Build Project on Trigger

on:
  workflow_dispatch: { }
defaults:
  run:
    shell: cmd
    
jobs:
  buildForWindowsBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: [ self-hosted, Windows, x64 ]
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: [ 'StandaloneWindows64' ] # Build a Windows 64-bit standalone.
        buildMethod:
          - CustomBuild.BuildForWindows
        unityVersion: [ '2023.2.14f1' ]
        localProjectPath:
          - 'Corraine\Documents\HAL\[011]GradExhibit\MS_Project\MS_Project'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: recursive
          
      - name: Setup Unity
        run: |
        echo "Setting up Unity"
        set PATH=%PATH%;C:\Program Files\Unity\Editor\${{ matrix.unityVersion }}\Editor

      - name: Build Project
        run: |
          set LOG_FILE="C:\Users\${{ matrix.localProjectPath }}\Builds\build-${{ github.run_id }}-${{ github.event.head_commit.timestamp }}.log"
          "C:\Program Files\Unity\Hub\Editor\${{ matrix.unityVersion }}\Editor\Unity.exe" -batchmode -quit -projectPath "C:\Users\${{ matrix.localProjectPath }}" -executeMethod ${{ matrix.buildMethod }} -nographics -logFile %LOG_FILE% -buildTarget ${{ matrix.targetPlatform }}
      - name: Upload App
        uses: actions/upload-artifact@v3
        with:
          name: DevelopmentBuild
          path: "C:\Users\${{ matrix.localProjectPath }}\Builds\*"
          retention-days: 7
          