name: Build Project on Trigger

on:
  workflow_dispatch: { }
defaults:
  run:
    shell: bash
    
jobs:
  buildForWindowsBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: [ self-hosted, Windows, x64 ]
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
        buildMethod:
          - CustomBuild.BuildForWindows
        unityPath:
          - '"C:\Program Files\Unity\Editor\2023.2.14f1\Editor\Unity.exe"'
        localProjectPath:
          - '"C:\Users\Corraine\Documents\HAL\[011]GradExhibit\MS_Project\MS_Project"'
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          submodules: recursive

      - name: Run Build
        run: |
          ${{ matrix.unityPath }} -batchmode -quit -projectPath ${{ matrix.localProjectPath }} -executeMethod ${{ matrix.buildMethod }} -nographics -logFile

      - name: Upload App
        uses: actions/upload-artifact@v3
        with:
          name: DevelopmentBuild
          path: Builds/Development/
          retention-days: 7
          