name: Build Project on Trigger
on:
  workflow_dispatch: { }
defaults:
  run:
    shell: powershell
    
jobs:
  buildApplication:
    name: Build Application
    runs-on: [ self-hosted, Windows, x64 ]
    strategy:
      fail-fast: false
      matrix:
        localProjectPath:
          - 'Corraine\Documents\HAL\GradExhibit\MS_Project\MS_Project'
        unityVersion: [ '2023.2.14f1' ]
        targetPlatform: [ 'StandaloneWindows64' ]
        buildMethod:
          - CustomBuild.BuildForWindows
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: false
          submodules: recursive
          
      - name: Setup Unity
        run: |
          Write-Host "Setting up Unity"
          $env:PATH += ";C:\Program Files\Unity\Editor\${{ matrix.unityVersion }}\Editor"

      - name: Build Project
        run: |
          $logFile = "C:\Users\${{ matrix.localProjectPath }}\Build\Logs\build-${{ github.run_id }}.log"
          & "C:\Program Files\Unity\Editor\${{ matrix.unityVersion }}\Editor\Unity.exe" -batchmode -quit -projectPath "C:\Users\${{ matrix.localProjectPath }}" -executeMethod ${{ matrix.buildMethod }} -nographics -logFile $logFile -buildTarget ${{ matrix.targetPlatform }}

  compressFiles:
    needs: buildApplication
    name: Compress Files
    runs-on: [ self-hosted, Windows, x64 ]
    strategy:
      fail-fast: false
      matrix:
        localProjectPath:
          - 'Corraine\Documents\HAL\GradExhibit\MS_Project\MS_Project'
        localDestPath:
          - 'Corraine\Documents\HAL\GradExhibit'
        targetPlatform: [ 'StandaloneWindows64' ]
    steps:
      - name: List Build Directory
        run:  |
          Get-ChildItem -Path "C:\Users\${{ matrix.localProjectPath }}\Build\Windows\*"

      - name: Compress Build Files
        run: |
          $zipFile = "C:\Users\${{ matrix.localDestPath }}\Build\Build-${{ github.run_id }}.zip"
          Compress-Archive -Path "C:\Users\${{ matrix.localProjectPath }}\Build\Windows\*" -DestinationPath $zipFile

  uploadFiles:
    needs: [ buildApplication, compressFiles ]
    name: Upload Files
    runs-on: [ self-hosted, Windows, x64 ]
    strategy:
      fail-fast: false
      matrix:
        localDestPath:
          - 'Corraine\Documents\HAL\GradExhibit'
    steps:
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: DevelopmentBuild-${{ github.run_id }}
          path: C:\Users\${{ matrix.localDestPath }}\Build\Build-${{ github.run_id }}.zip
          retention-days: 7
          